---
- name: Backup MongoDB and Redis (+ Uptime Kuma volume on k3s host)
  hosts: ircfiber_backend:ircfiber_k3s
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../inventories/production/group_vars/vault.yml"
  roles:
    - role: backup
